version: "2"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    links:
      - mongo_db:app_db
  mongo_db:
    image: "mongo:5.0.6"
    restart: always
    ports:
      - 27017:27017
